### ISSUE TITLE
Bug: build process to minify JS is stuck in an infinite loop

### ISSUE THREAD

**Issue by hanopcan** [thegreenwebfoundation/tgwf-2020#8]
Trello card with internal convos: https://trello.com/c/GiuJKFs8/198-sort-out-website-themes-tooling

When I run `npm watch-bs` the js minification gets immediately stuck in an infinite loop. Terminal output looks a bit like this:

![Screenshot 2024-07-24 at 13 44 12](https://github.com/user-attachments/assets/a6c2df61-fe45-4766-816b-219ab20ebd8e)

For now I have amended our package.json file to only run the css processes when we do `npm watch-bs` - https://github.com/thegreenwebfoundation/tgwf-2020/blob/002a042a99037b8b51b5f1889e98c44f0ae0cec5/package.json#L14

The end part of that line should run `watch-run-*` instead of `watch-run-css`.

Ideally though I'd like to get to the bottom of this issue so that we are able to minify our CSS and JS properly.

Code so far has been based on Understrap's approach, but modified to remove the bootstrap dependencies and simplfy stuff to just what we need. https://github.com/understrap/understrap/blob/main/package.json

**Comment by fershad** [comment]
@hanopcan I believe this was being caused by the output file `theme.min.js` being in the same folder that was being watched by nodemon. As a result, the minified file would be generated which would make nodemon think that there was a new JS file in the folder, which would then trigger the JS minification step again.

I've added some ignore code to the `package.json` file to prevent this https://github.com/thegreenwebfoundation/tgwf-2020/pull/9/commits/506a22987cf5cfa49255ccd320565aca0cc82b21 

I've made the change and added it to the PR #9

**Comment by hanopcan** [comment]
@fershad You are a super star thank you. Slightly embarassed I didn't spot that. Away now for the week, so will will review and merge the PR when I'm back. Thank you for the fresh eyes.

**Comment by hanopcan** [comment]
This has been resolved and all is well. CLosing this off.
